version: '3.4'

services:
  scheduler.web:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=$CONNECTION_STRING
    ports:
      - "80"
      - "443"