version: '3.4'

services:
  scheduler.web:
    container_name: schedulerweb
    image: profjordanov/schedulerweb:latest
    build:
      context: .
      dockerfile: Scheduler.Web/Dockerfile

  scheduler.logging:
    container_name: schedulerlogging
    image:  profjordanov/schedulerlogging:latest
    build:
      context: .
      dockerfile: Scheduler.Logging/Dockerfile

